# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-03 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='trip_id',
            new_name='trip',
        ),
        migrations.AddField(
            model_name='reminder',
            name='reminder_time',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
    ]
