# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-03 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_pid', models.CharField(max_length=255)),
                ('to_pid', models.CharField(max_length=255)),
                ('from_text', models.CharField(max_length=255)),
                ('to_text', models.CharField(max_length=255)),
            ],
        ),
    ]
